-- Presencia online (Realtime)
-- En Supabase Dashboard → Project Settings → API → Realtime: debe estar activo.
-- No requiere tablas extra: usa Supabase Realtime Presence (canal global-online).
-- Para "última conexión", ejecuta también supabase/last-seen.sql.
